
package com.topo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IrmsTopoShareServiceService", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService", wsdlLocation = "file:/C:/Users/Admin/AppData/Local/Temp/tempdir7773613289252880988.tmp/IrmsTopoShareService_1.wsdl")
public class IrmsTopoShareServiceService
    extends Service
{

    private final static URL IRMSTOPOSHARESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException IRMSTOPOSHARESERVICESERVICE_EXCEPTION;
    private final static QName IRMSTOPOSHARESERVICESERVICE_QNAME = new QName("http://services.irms.nrmds.iman.com/TimeService", "IrmsTopoShareServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Admin/AppData/Local/Temp/tempdir7773613289252880988.tmp/IrmsTopoShareService_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IRMSTOPOSHARESERVICESERVICE_WSDL_LOCATION = url;
        IRMSTOPOSHARESERVICESERVICE_EXCEPTION = e;
    }

    public IrmsTopoShareServiceService() {
        super(__getWsdlLocation(), IRMSTOPOSHARESERVICESERVICE_QNAME);
    }

    public IrmsTopoShareServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IRMSTOPOSHARESERVICESERVICE_QNAME, features);
    }

    public IrmsTopoShareServiceService(URL wsdlLocation) {
        super(wsdlLocation, IRMSTOPOSHARESERVICESERVICE_QNAME);
    }

    public IrmsTopoShareServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IRMSTOPOSHARESERVICESERVICE_QNAME, features);
    }

    public IrmsTopoShareServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IrmsTopoShareServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimeService
     */
    @WebEndpoint(name = "TimeServicePort")
    public TimeService getTimeServicePort() {
        return super.getPort(new QName("http://services.irms.nrmds.iman.com/TimeService", "TimeServicePort"), TimeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeService
     */
    @WebEndpoint(name = "TimeServicePort")
    public TimeService getTimeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.irms.nrmds.iman.com/TimeService", "TimeServicePort"), TimeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IRMSTOPOSHARESERVICESERVICE_EXCEPTION!= null) {
            throw IRMSTOPOSHARESERVICESERVICE_EXCEPTION;
        }
        return IRMSTOPOSHARESERVICESERVICE_WSDL_LOCATION;
    }

}
