
package com.topo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeService", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeService {


    /**
     * 
     * @param nodeName
     * @param serCaller
     * @param topoId
     * @param nodeId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TopoVersionUpdateService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "TopoVersionUpdateService", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService", className = "com.topo.TopoVersionUpdateService")
    @ResponseWrapper(localName = "TopoVersionUpdateServiceResponse", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService", className = "com.topo.TopoVersionUpdateServiceResponse")
    public String topoVersionUpdateService(
        @WebParam(name = "serCaller", targetNamespace = "")
        String serCaller,
        @WebParam(name = "topoId", targetNamespace = "")
        String topoId,
        @WebParam(name = "nodeName", targetNamespace = "")
        String nodeName,
        @WebParam(name = "nodeId", targetNamespace = "")
        String nodeId);

    /**
     * 
     * @param serCaller
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "imagesVersionUpdateService", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService", className = "com.topo.ImagesVersionUpdateService")
    @ResponseWrapper(localName = "imagesVersionUpdateServiceResponse", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService", className = "com.topo.ImagesVersionUpdateServiceResponse")
    public String imagesVersionUpdateService(
        @WebParam(name = "serCaller", targetNamespace = "")
        String serCaller);

    /**
     * 
     * @param serCaller
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "menuService", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService", className = "com.topo.MenuService")
    @ResponseWrapper(localName = "menuServiceResponse", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService", className = "com.topo.MenuServiceResponse")
    public String menuService(
        @WebParam(name = "serCaller", targetNamespace = "")
        String serCaller);

    /**
     * 
     * @param nodeName
     * @param serCaller
     * @param topoId
     * @param nodeId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "topoService", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService", className = "com.topo.TopoService")
    @ResponseWrapper(localName = "topoServiceResponse", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService", className = "com.topo.TopoServiceResponse")
    public String topoService(
        @WebParam(name = "serCaller", targetNamespace = "")
        String serCaller,
        @WebParam(name = "topoId", targetNamespace = "")
        String topoId,
        @WebParam(name = "nodeName", targetNamespace = "")
        String nodeName,
        @WebParam(name = "nodeId", targetNamespace = "")
        String nodeId);

    /**
     * 
     * @param serCaller
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "topoImages", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService", className = "com.topo.TopoImages")
    @ResponseWrapper(localName = "topoImagesResponse", targetNamespace = "http://services.irms.nrmds.iman.com/TimeService", className = "com.topo.TopoImagesResponse")
    public String topoImages(
        @WebParam(name = "serCaller", targetNamespace = "")
        String serCaller);

}
